# Generated by Django 4.1.4 on 2023-07-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
