# Generated by Django 4.1.4 on 2023-07-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers_api', '0003_rename_centers_center_rename_devices_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Center',
            new_name='Centers',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AddField(
            model_name='devices',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='centers_api.centers'),
        ),
    ]
