# Generated by Django 4.1.4 on 2023-07-31 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers_api', '0004_devices_rename_center_centers_delete_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('NA', 'NONE'), ('SV', 'SERVICE')], default='NA', max_length=2)),
                ('description', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='centers_api.devices')),
            ],
        ),
    ]
