# Generated by Django 4.1.4 on 2023-08-03 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centers_api', '0006_devices_bundle_version_devices_system_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
