# Generated by Django 4.1.4 on 2023-08-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers_api', '0007_devicefiles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='name',
            field=models.TextField(default='Hi', max_length=100),
            preserve_default=False,
        ),
    ]
