# Generated by Django 4.1.4 on 2023-10-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers_api', '0008_devices_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='installation_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='model',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='serial_number',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
