# Generated by Django 4.1.4 on 2023-12-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers_api', '0011_historicaldevicehints_devicehints'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehints',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldevicehints',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
    ]
