# Generated by Django 4.1.4 on 2023-01-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('surgery_date', models.DateField()),
                ('surgery_day', models.IntegerField()),
                ('surgery_time', models.IntegerField()),
                ('surgery_type', models.CharField(max_length=100)),
                ('surgery_area', models.IntegerField()),
                ('surgery_description', models.CharField(max_length=100)),
                ('surgery_result', models.IntegerField()),
                ('surgeon_first', models.CharField(max_length=100)),
                ('surgeon_second', models.CharField(max_length=100)),
                ('resident', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('hospital_type', models.IntegerField()),
                ('hospital_address', models.CharField(max_length=100)),
                ('ct', models.IntegerField()),
                ('mr', models.IntegerField()),
                ('fmri', models.IntegerField()),
                ('dti', models.IntegerField()),
                ('operator_first', models.CharField(max_length=100)),
                ('operator_second', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('enter_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('patient_enter_time', models.TimeField()),
                ('head_fix_type', models.IntegerField()),
                ('cancellation_reason', models.CharField(max_length=100)),
                ('file_number', models.CharField(max_length=100)),
                ('date_of_hospital_admission', models.DateField()),
                ('payment_status', models.IntegerField()),
                ('date_of_first_contact', models.DateField()),
                ('payment_note', models.CharField(max_length=100)),
                ('first_caller', models.CharField(max_length=100)),
                ('date_of_payment', models.DateField()),
                ('last_four_digits_card', models.CharField(max_length=100)),
                ('cash_amount', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('discount_percent', models.FloatField()),
                ('reason_for_discount', models.CharField(max_length=100)),
                ('health_plan_amount', models.CharField(max_length=100)),
                ('type_of_insurance', models.CharField(max_length=100)),
                ('financial_verifier', models.CharField(max_length=100)),
                ('receipt_number', models.IntegerField()),
                ('fre', models.FloatField()),
            ],
        ),
    ]
