# Generated by Django 4.1.4 on 2023-11-11 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('family', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('national_id', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('place_of_birth', models.CharField(default='', max_length=100)),
                ('surgery_date', models.DateField(null=True)),
                ('surgery_day', models.IntegerField(null=True)),
                ('surgery_time', models.IntegerField(null=True)),
                ('surgery_type', models.CharField(default='', max_length=100)),
                ('surgery_area', models.IntegerField(null=True)),
                ('surgery_description', models.TextField(default='')),
                ('surgery_result', models.IntegerField(null=True)),
                ('surgeon_first', models.CharField(default='', max_length=100)),
                ('surgeon_second', models.CharField(default='', max_length=100)),
                ('resident', models.CharField(default='', max_length=100)),
                ('hospital', models.CharField(default='', max_length=100)),
                ('hospital_type', models.IntegerField(null=True)),
                ('hospital_address', models.CharField(default='', max_length=100)),
                ('ct', models.IntegerField(null=True)),
                ('mr', models.IntegerField(null=True)),
                ('fmri', models.IntegerField(null=True)),
                ('dti', models.IntegerField(null=True)),
                ('operator_first', models.CharField(default='', max_length=100)),
                ('operator_second', models.CharField(default='', max_length=100)),
                ('start_time', models.TimeField(null=True)),
                ('stop_time', models.TimeField(null=True)),
                ('enter_time', models.TimeField(null=True)),
                ('exit_time', models.TimeField(null=True)),
                ('patient_enter_time', models.TimeField(null=True)),
                ('head_fix_type', models.IntegerField(null=True)),
                ('cancellation_reason', models.CharField(default='', max_length=100)),
                ('file_number', models.CharField(default='', max_length=100)),
                ('date_of_hospital_admission', models.DateField(null=True)),
                ('payment_status', models.IntegerField(null=True)),
                ('date_of_first_contact', models.DateField(null=True)),
                ('payment_note', models.CharField(default='', max_length=100)),
                ('first_caller', models.CharField(default='', max_length=100)),
                ('date_of_payment', models.DateField(null=True)),
                ('last_four_digits_card', models.CharField(default='', max_length=100)),
                ('cash_amount', models.CharField(default='', max_length=100)),
                ('bank', models.CharField(default='', max_length=100)),
                ('discount_percent', models.FloatField(null=True)),
                ('reason_for_discount', models.CharField(default='', max_length=100)),
                ('health_plan_amount', models.CharField(default='', max_length=100)),
                ('type_of_insurance', models.CharField(default='', max_length=100)),
                ('financial_verifier', models.CharField(default='', max_length=100)),
                ('receipt_number', models.IntegerField(null=True)),
                ('fre', models.FloatField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical patient',
                'verbose_name_plural': 'historical patients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
