# Generated by Django 4.1.4 on 2023-01-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0002_alter_patient_address_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
