# Generated by Django 4.1.4 on 2023-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0002_historicalpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='surgery_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surgery_description',
            field=models.TextField(default=''),
        ),
    ]
