# Generated by Django 4.1.4 on 2023-11-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0003_alter_historicalpatient_surgery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='refund_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='refund_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
